#!/usr/bin/env python3
"""Generate all client adapters from data/vocabulary.json + core rule blocks.

Single source of truth: this script + vocabulary.json. Run after editing
either; commit the regenerated adapters/ files.

    python3 build_adapters.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VOCAB = json.loads((ROOT / "data" / "vocabulary.json").read_text())

HARD = VOCAB["hard_ban"]["words"]
STRONG = VOCAB["strong_flag"]["words"]
WATCH = VOCAB["density_watch"]["words"]

# Base forms for compact adapters (inflections covered by "and inflections")
HARD_BASE = ["delve", "tapestry", "showcase", "underscore", "meticulous",
             "commendable", "realm", "elucidate", "game-changer", "ever-evolving"]
STRONG_BASE = ["intricate", "pivotal", "testament", "vibrant", "boast", "garner",
               "bolster", "seamless", "groundbreaking", "cutting-edge", "invaluable",
               "leverage", "harness", "unveil", "transformative", "landscape"]


def wordlist(words: list[str], per_line: int = 8, indent: str = "  ") -> str:
    lines = []
    for i in range(0, len(words), per_line):
        lines.append(indent + ", ".join(words[i : i + per_line]) + ",")
    out = "\n".join(lines)
    return out.rstrip(",") if out.endswith(",") else out


CORE_RULES = f"""VOCABULARY
- Never use these words (measured AI markers):
{wordlist(HARD)}
- Use these sparingly, at most one per document, only with cause:
{wordlist(STRONG)}
- Watch the density of these common words; a cluster in one paragraph is a tell:
{wordlist(WATCH)}
- Write "is", "are", "has" instead of "serves as", "stands as", "boasts",
  "represents", "features", "marks".

RHYTHM AND PUNCTUATION
- Mix sentence lengths: some under 10 words, some over 20. Never three
  consecutive sentences of similar length.
- Vary paragraph length. A one-sentence paragraph is allowed.
- No em-dashes. Use commas, periods, or parentheses.
- No "not X, but Y" or "it's not just X, it's Y" constructions. Make the
  positive assertion directly.
- Avoid compulsive three-item lists. Vary: two items, four, or none.

SUBSTANCE
- Every abstract claim gets a number, name, date, or example within two
  sentences. If none exists, write [NEEDS EXAMPLE] instead of padding.
- Name sources. Never "studies show" or "experts say" without saying which.
- Take a position where the material supports one, and give the reason.
  No symmetric hedging unless genuinely undecided; then say why.
- Push back when a premise looks wrong. Do not agree by default.

STRUCTURE
- No throat-clearing openers ("It's worth noting", "In today's world").
  Start where the point starts.
- No closing bows ("In conclusion", "Overall"). Stop where the point ends.
- No bullet lists or markdown in prose contexts unless asked.

SELF-CHECK
- Before finishing, re-scan the output for em-dashes, banned words, and
  three similar-length sentences in a row. Fix what you find.

REGISTER EXCEPTION
- For formal or academic targets, keep necessary passive voice and relax
  the sentence-length rules. Genre wins over these defaults."""

COMPACT_RULES = f"""- Never use: {", ".join(HARD_BASE)} (or their inflections).
- Ration (max one per document): {", ".join(STRONG_BASE)}.
- Write is/are/has, never "serves as / stands as / boasts / represents".
- No em-dashes. No "not X, but Y" constructions; assert directly.
- Mix sentence lengths; never three similar-length sentences in a row. Vary paragraph length.
- Concrete over abstract: numbers, names, dates, examples. Name sources; never "studies show" alone.
- Take positions with reasons. No symmetric hedging. Push back on wrong premises.
- No throat-clearing openers or "In conclusion" wrap-ups. No compulsive three-item lists.
- Before finishing prose, re-scan for em-dashes and banned words; fix them."""

HEADER = (
    "<!-- Generated by build_adapters.py from data/vocabulary.json. "
    "Do not edit by hand; edit the source and regenerate. -->"
)

ADAPTERS: dict[str, str] = {}

# ── Generic system prompt (any client) ───────────────────────────────────────
ADAPTERS["SYSTEM_PROMPT.md"] = f"""{HEADER}
# Writing-style constraints (anti-AI-tell, generation time)

Paste this block into the system prompt or custom instructions of any AI
client. It is the Tier-0 layer of the anti-ai-tell discipline: it prevents
AI-ese at the source. The mechanical linter and the judgment checklist live
in the repo root.

---

WRITING STYLE RULES (apply to all prose you produce for me):

{CORE_RULES}
"""

# ── AGENTS.md (open agent standard: Codex CLI, Jules, Amp, Devin, etc.) ──────
ADAPTERS["AGENTS.md"] = f"""{HEADER}
# Writing style: anti-AI-tell

When producing any prose for humans (docs, READMEs, commit messages, PR
descriptions, comments, user-facing strings, reports), follow these rules.
Code is exempt; prose is not.

{CORE_RULES}

Linter available: `python3 skills/anti-ai-tell/lint.py FILE` flags violations
mechanically (13 checks, CI-gateable). Run it on prose before finishing.
"""

# ── GitHub Copilot ────────────────────────────────────────────────────────────
ADAPTERS["copilot-instructions.md"] = f"""{HEADER}
# Copilot instructions: prose style (anti-AI-tell)

Install: copy into `.github/copilot-instructions.md` (repo-wide) or merge the
block into an existing instructions file.

When writing prose (docs, comments, commit messages, PR text):

{COMPACT_RULES}
"""

# ── Cursor ────────────────────────────────────────────────────────────────────
ADAPTERS["cursor-rules.mdc"] = f"""---
description: Anti-AI-tell writing rules. Apply to all prose output (docs, comments, commit messages, README content, user-facing strings).
globs:
alwaysApply: true
---
{HEADER}

# Writing style: no AI tells

When writing any prose (documentation, READMEs, comments, commit messages,
PR descriptions, user-facing copy):

{COMPACT_RULES}
"""

# ── Cline / Roo Code ─────────────────────────────────────────────────────────
ADAPTERS["clinerules.md"] = f"""{HEADER}
# Anti-AI-tell writing rules (install as .clinerules in project root)

When writing prose (docs, comments, commit messages, user-facing text):

{COMPACT_RULES}
"""

# ── Windsurf ──────────────────────────────────────────────────────────────────
ADAPTERS["windsurf-rules.md"] = f"""{HEADER}
# Anti-AI-tell writing rules
# Install: copy to .windsurf/rules/anti-ai-tell.md (activation: always on)

When writing prose (docs, comments, commit messages, user-facing text):

{COMPACT_RULES}
"""

# ── Gemini CLI ────────────────────────────────────────────────────────────────
ADAPTERS["GEMINI.md"] = f"""{HEADER}
# Writing style: anti-AI-tell
# Install: merge into project GEMINI.md or ~/.gemini/GEMINI.md

When producing prose for humans:

{CORE_RULES}
"""

# ── Aider ─────────────────────────────────────────────────────────────────────
ADAPTERS["CONVENTIONS.md"] = f"""{HEADER}
# Prose conventions (anti-AI-tell)
# Install: add to aider via `aider --read CONVENTIONS.md` or .aider.conf.yml read:

When writing prose (docs, comments, commit messages):

{COMPACT_RULES}
"""

# ── Zed ───────────────────────────────────────────────────────────────────────
ADAPTERS["zed-rules.md"] = f"""{HEADER}
# Anti-AI-tell writing rules (install as .rules in project root; Zed reads it)

When writing prose (docs, comments, commit messages, user-facing text):

{COMPACT_RULES}
"""

# ── CLAUDE.md snippet (projects that skip the plugin) ────────────────────────
ADAPTERS["CLAUDE.md-snippet.md"] = f"""{HEADER}
# Anti-AI-tell snippet for CLAUDE.md
# Install: paste the block below into your project or user CLAUDE.md.
# (Prefer the Claude Code plugin for the full skill + linter.)

## Prose style (anti-AI-tell)

For external/human-read prose (READMEs, docs, issue and PR bodies, email,
marketing copy):

{COMPACT_RULES}
"""

# ── ChatGPT custom instructions (hard ~1500-char field limit) ────────────────
chatgpt = f"""Writing rules for all prose: Never use {", ".join(HARD_BASE)} or their inflections. At most one per document of: {", ".join(STRONG_BASE[:12])}. Write is/are/has, not "serves as/stands as/boasts/represents". No em-dashes; use commas, periods, parentheses. No "not X, but Y" constructions; assert directly. Mix sentence lengths (some under 10 words, some over 20); never three similar-length sentences in a row; vary paragraph length. Concrete over abstract: numbers, names, dates, examples; name sources, never "studies show" alone. Take positions with reasons; no symmetric hedging; push back on wrong premises. No openers like "It's worth noting"; no "In conclusion" endings. No compulsive three-item lists. Before finishing, re-scan for em-dashes and banned words and fix them. For formal/academic targets keep necessary passives; genre wins."""
assert len(chatgpt) <= 1500, f"ChatGPT block too long: {len(chatgpt)}"
ADAPTERS["chatgpt-custom-instructions.txt"] = chatgpt + "\n"


FOOTER = "<!-- /anti-ai-tell (end of generated block) -->\n"


def main() -> None:
    outdir = ROOT / "adapters"
    outdir.mkdir(exist_ok=True)
    for name, content in ADAPTERS.items():
        if name.endswith((".md", ".mdc")):
            content = content.rstrip() + "\n" + FOOTER
        (outdir / name).write_text(content, encoding="utf-8")
        print(f"wrote adapters/{name} ({len(content)} chars)")


if __name__ == "__main__":
    main()
